const express = require('express');
const Database = require('better-sqlite3');
const path = require('path');
const db = new Database(path.join(__dirname, 'eququest.sqlite'));
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS students (
  id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL,
  xp INTEGER NOT NULL DEFAULT 0, coins INTEGER NOT NULL DEFAULT 0, hearts INTEGER NOT NULL DEFAULT 5,
  streak INTEGER NOT NULL DEFAULT 0, solved INTEGER NOT NULL DEFAULT 0, current_unit INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)`);
db.exec(`CREATE TABLE IF NOT EXISTS teachers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, preferences TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
db.prepare("INSERT OR IGNORE INTO teachers(name,email,preferences) VALUES('Professor Demo','professor.demo@eququest.local','{\"feedback\":true,\"difficulty\":true}')").run();
db.exec(`CREATE TABLE IF NOT EXISTS questions (
  id INTEGER PRIMARY KEY AUTOINCREMENT, unit INTEGER NOT NULL, level TEXT NOT NULL,
  type TEXT NOT NULL, prompt TEXT NOT NULL, answer TEXT NOT NULL, solution TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL, question_id INTEGER,
  answer TEXT, correct INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(student_id) REFERENCES students(id), FOREIGN KEY(question_id) REFERENCES questions(id)
);`);
db.exec(`CREATE TABLE IF NOT EXISTS classes (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, teacher TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS class_members (class_id INTEGER NOT NULL, student_id INTEGER NOT NULL, UNIQUE(class_id,student_id));
CREATE TABLE IF NOT EXISTS class_assignments (class_id INTEGER NOT NULL, unit INTEGER NOT NULL, UNIQUE(class_id,unit));`);
db.exec(`CREATE TABLE IF NOT EXISTS activities (id INTEGER PRIMARY KEY AUTOINCREMENT, class_id INTEGER NOT NULL, title TEXT NOT NULL, unit INTEGER NOT NULL, due_date TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
try { db.exec('ALTER TABLE attempts ADD COLUMN unit INTEGER'); } catch {}
const questionCount=db.prepare('SELECT COUNT(*) AS total FROM questions').get().total;
if(!questionCount){const add=db.prepare('INSERT INTO questions (unit,level,type,prompt,answer,solution) VALUES (?,?,?,?,?,?)');const seed=db.transaction(()=>[
  [1,'basic','solve','x + 3 = 8','5','Subtraia 3 dos dois lados: x = 5.'],[1,'basic','solve','x − 4 = 10','14','Some 4 aos dois lados: x = 14.'],[1,'medium','true_false','x = 7 é solução de 2x + 3 = 17?','true','Substituindo: 2(7)+3 = 17.'],
  [2,'basic','operation','x + 7 = 15','−7','A operação inversa de +7 é −7.'],[2,'medium','solve','x − 6 = 11','17','Some 6 aos dois lados: x = 17.'],[2,'advanced','find_error','3x + 6 = 21; 3x = 21','erro no primeiro passo','É preciso subtrair 6 antes de dividir.'],
  [3,'basic','solve','3x = 15','5','Divida os dois lados por 3: x = 5.'],[3,'medium','solve','x / 4 = 6','24','Multiplique os dois lados por 4: x = 24.'],[4,'basic','solve','2x + 4 = 14','5','Subtraia 4 e divida por 2: x = 5.'],
  [4,'medium','solve','3x − 6 = 15','7','Some 6 e divida por 3: x = 7.'],[5,'medium','solve','2(x + 3) = 18','6','Divida por 2 e subtraia 3: x = 6.'],[6,'advanced','solve','5x + 2 = 2x + 17','5','Subtraia 2x, subtraia 2 e divida por 3: x = 5.']
].forEach(row=>add.run(...row)));seed();}
// Complementa o banco até 100 questões com variações matematicamente válidas.
const totalQuestions=db.prepare('SELECT COUNT(*) AS total FROM questions').get().total;
if(totalQuestions<100){const add=db.prepare('INSERT INTO questions (unit,level,type,prompt,answer,solution) VALUES (?,?,?,?,?,?)');const fill=db.transaction(()=>{let n=totalQuestions;for(let unit=1;unit<=7&&n<100;unit++){const target=unit<=6?15:10;let made=0;for(let i=1;made<target&&n<100;i++){const a=(i%9)+2,b=(i*3%14)+3,c=a*i+b;let level=i%5===0?'advanced':i%2===0?'medium':'basic',type=i%4===0?'complete':i%3===0?'true_false':'solve',prompt,answer,solution;if(unit===1){prompt=`x + ${b} = ${c}`;answer=String(a*i);solution=`Subtraia ${b} dos dois lados: x = ${answer}.`;}else if(unit===2){prompt=`x − ${b} = ${c}`;answer=String(c+b);solution=`Some ${b} aos dois lados: x = ${answer}.`;}else if(unit===3){prompt=`${a}x = ${a*(i+2)}`;answer=String(i+2);solution=`Divida os dois lados por ${a}: x = ${answer}.`;}else if(unit===4){prompt=`${a}x + ${b} = ${a*(i+2)+b}`;answer=String(i+2);solution=`Subtraia ${b} e divida por ${a}: x = ${answer}.`;}else if(unit===5){prompt=`${a}(x + ${b}) = ${a*(i+2+b)}`;answer=String(i+2);solution=`Divida por ${a} e subtraia ${b}: x = ${answer}.`;}else if(unit===6){prompt=`${a}x + ${b} = ${a-1}x + ${a*(i+2)+b}`;answer=String(i+2);solution=`Reúna os termos com x e isole a incógnita: x = ${answer}.`;}else{prompt=`${a}x − ${b} = ${a*(i+2)-b}`;answer=String(i+2);solution=`Some ${b} e divida por ${a}: x = ${answer}.`;}if(type==='true_false'){prompt+=`  (x = ${answer})`;answer='true';}if(type==='complete')prompt+=`  → x = ___`;add.run(unit,level,type,prompt,answer,solution);made++;n++;}}});fill();}
if(db.prepare('SELECT COUNT(*) total FROM questions WHERE unit=7').get().total<10){const add7=db.prepare('INSERT INTO questions (unit,level,type,prompt,answer,solution) VALUES (7,?,?,?, ?,?)');for(let i=1;i<=10;i++){const answer=String(i+2);add7.run(i%2?'advanced':'medium','solve',`${i+2}x − ${i+1} = ${(i+2)*(i+3)-(i+1)}`,answer,`Some ${i+1} e divida por ${i+2}: x = ${answer}.`);}}
const app = express(); app.use(express.json());
app.post('/api/students', (req,res)=>{
  const name=String(req.body.name||'').trim(), email=String(req.body.email||'').trim().toLowerCase();
  if(!name||!email||!email.includes('@')) return res.status(400).json({error:'Nome e e-mail são obrigatórios.'});
  let student=db.prepare('SELECT * FROM students WHERE email=?').get(email);
  if(!student){ const r=db.prepare('INSERT INTO students (name,email,coins) VALUES (?,?,?)').run(name,email,230); student=db.prepare('SELECT * FROM students WHERE id=?').get(r.lastInsertRowid); }
  res.json(student);
});
app.post('/api/teachers',(req,res)=>{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase();if(!name||!email)return res.status(400).json({error:'Nome e e-mail são obrigatórios.'});db.prepare('INSERT OR IGNORE INTO teachers(name,email) VALUES(?,?)').run(name,email);res.json(db.prepare('SELECT * FROM teachers WHERE email=?').get(email));});
app.get('/api/teachers/:email',(req,res)=>{const t=db.prepare('SELECT * FROM teachers WHERE email=?').get(req.params.email);t?res.json(t):res.status(404).json({error:'Professor não encontrado.'});});
app.get('/api/questions', (req,res)=>{const unit=Number(req.query.unit);res.json(db.prepare(unit?'SELECT * FROM questions WHERE unit=? ORDER BY id':'SELECT * FROM questions ORDER BY unit,id').all(...(unit?[unit]:[])));});
app.post('/api/attempts',(req,res)=>{const {student_id,question_id,unit,answer,correct}=req.body;if(!student_id)return res.status(400).json({error:'student_id obrigatório'});const r=db.prepare('INSERT INTO attempts (student_id,question_id,unit,answer,correct) VALUES (?,?,?,?,?)').run(student_id,question_id||null,unit||null,String(answer??''),correct?1:0);res.json({id:r.lastInsertRowid});});
app.get('/api/students/:id/performance',(req,res)=>{const summary=db.prepare('SELECT COUNT(*) attempts, COALESCE(SUM(correct),0) correct FROM attempts WHERE student_id=?').get(req.params.id);const byUnit=db.prepare('SELECT COALESCE(unit,0) unit,COUNT(*) attempts,SUM(correct) correct FROM attempts WHERE student_id=? GROUP BY unit ORDER BY (CAST(SUM(correct) AS REAL)/COUNT(*)) ASC').all(req.params.id);res.json({summary,byUnit});});
app.post('/api/classes',(req,res)=>{const name=String(req.body.name||'').trim(),teacher=String(req.body.teacher||'').trim();if(!name||!teacher)return res.status(400).json({error:'Nome da turma e professor são obrigatórios.'});const r=db.prepare('INSERT INTO classes(name,teacher) VALUES(?,?)').run(name,teacher);res.json(db.prepare('SELECT * FROM classes WHERE id=?').get(r.lastInsertRowid));});
app.get('/api/classes',(req,res)=>res.json(db.prepare('SELECT c.*,COUNT(cm.student_id) students FROM classes c LEFT JOIN class_members cm ON cm.class_id=c.id GROUP BY c.id ORDER BY c.id DESC').all()));
app.get('/api/classes/:id/overview',(req,res)=>{const students=db.prepare(`SELECT s.id,s.name,s.email,s.xp,s.solved,s.current_unit,COUNT(a.id) attempts,COALESCE(SUM(a.correct),0) correct FROM class_members cm JOIN students s ON s.id=cm.student_id LEFT JOIN attempts a ON a.student_id=s.id WHERE cm.class_id=? GROUP BY s.id`).all(req.params.id);const details=students.map(s=>({...s,accuracy:s.attempts?Math.round(s.correct/s.attempts*100):0,weakest:db.prepare('SELECT unit,COUNT(*) attempts,SUM(correct) correct FROM attempts WHERE student_id=? GROUP BY unit ORDER BY CAST(SUM(correct) AS REAL)/COUNT(*) ASC LIMIT 1').get(s.id)||null}));res.json({students:details});});
app.get('/api/classes/:id/activities',(req,res)=>res.json(db.prepare('SELECT * FROM activities WHERE class_id=? ORDER BY created_at DESC').all(req.params.id)));
app.post('/api/classes/:id/activities',(req,res)=>{const title=String(req.body.title||'').trim(),unit=Number(req.body.unit),due=req.body.due_date||null;if(!title||!unit)return res.status(400).json({error:'Título e unidade são obrigatórios.'});const r=db.prepare('INSERT INTO activities(class_id,title,unit,due_date) VALUES(?,?,?,?)').run(req.params.id,title,unit,due);res.json(db.prepare('SELECT * FROM activities WHERE id=?').get(r.lastInsertRowid));});
app.get('/api/classes/:id/members',(req,res)=>res.json(db.prepare('SELECT s.id,s.name,s.email FROM class_members cm JOIN students s ON s.id=cm.student_id WHERE cm.class_id=? ORDER BY s.name').all(req.params.id)));
app.post('/api/classes/:id/members',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),s=db.prepare('SELECT id,name,email FROM students WHERE email=?').get(email);if(!s)return res.status(404).json({error:'Aluno não encontrado. Crie o perfil do aluno antes de adicioná-lo.'});db.prepare('INSERT OR IGNORE INTO class_members(class_id,student_id) VALUES(?,?)').run(req.params.id,s.id);res.json(s);});
app.get('/api/students/:id/classes',(req,res)=>res.json(db.prepare(`SELECT c.id,c.name,c.teacher,ca.unit FROM class_members cm JOIN classes c ON c.id=cm.class_id LEFT JOIN class_assignments ca ON ca.class_id=c.id WHERE cm.student_id=? ORDER BY c.name,ca.unit`).all(req.params.id)));
app.post('/api/classes/:id/assignments',(req,res)=>{const unit=Number(req.body.unit);if(!unit)return res.status(400).json({error:'Unidade obrigatória.'});db.prepare('INSERT OR IGNORE INTO class_assignments(class_id,unit) VALUES(?,?)').run(req.params.id,unit);res.json({ok:true});});
app.post('/api/mock',(req,res)=>{const students=[['Ana Demo','ana.demo@eququest.local'],['Bruno Demo','bruno.demo@eququest.local'],['Carla Demo','carla.demo@eququest.local']];const ids=students.map(([name,email],i)=>{let s=db.prepare('SELECT * FROM students WHERE email=?').get(email);if(!s){const r=db.prepare('INSERT INTO students(name,email,xp,coins,solved,current_unit) VALUES(?,?,?,?,?,?)').run(name,email,180+i*120,230+i*20,4+i*3,1+i);s=db.prepare('SELECT * FROM students WHERE id=?').get(r.lastInsertRowid)}return s.id});const sample=[['Lucas Teste','lucas.teste@eququest.local'],['Marina Teste','marina.teste@eququest.local'],['João Teste','joao.teste@eququest.local'],['Sofia Teste','sofia.teste@eququest.local'],['Ravi Teste','ravi.teste@eququest.local'],['Bia Teste','bia.teste@eququest.local'],['Pedro Teste','pedro.teste@eququest.local'],['Lia Teste','lia.teste@eququest.local'],['Davi Teste','davi.teste@eququest.local'],['Nina Teste','nina.teste@eququest.local']];sample.forEach(([name,email],i)=>db.prepare('INSERT OR IGNORE INTO students(name,email,xp,coins,solved,current_unit) VALUES(?,?,?,?,?,?)').run(name,email,i*40,230,0,1));let turma=db.prepare("SELECT * FROM classes WHERE name='Turma demonstração'").get();if(!turma){const r=db.prepare("INSERT INTO classes(name,teacher) VALUES('Turma demonstração','Professor Demo')").run();turma=db.prepare('SELECT * FROM classes WHERE id=?').get(r.lastInsertRowid)}ids.forEach(id=>db.prepare('INSERT OR IGNORE INTO class_members(class_id,student_id) VALUES(?,?)').run(turma.id,id));[1,2,3,4].forEach(unit=>db.prepare('INSERT OR IGNORE INTO class_assignments(class_id,unit) VALUES(?,?)').run(turma.id,unit));const add=db.prepare('INSERT INTO attempts(student_id,unit,answer,correct) VALUES(?,?,?,?)');ids.forEach((id,i)=>{for(let n=0;n<8;n++)add.run(id,(n%4)+1,String(n+i),n%((i+2))!==0?1:0)});res.json({ok:true,class_id:turma.id,students:ids.length,available_students:sample.length});});
app.get('/api/students/:id', (req,res)=>{const s=db.prepare('SELECT * FROM students WHERE id=?').get(req.params.id); s?res.json(s):res.status(404).json({error:'Aluno não encontrado.'});});
app.patch('/api/students/:id', (req,res)=>{const allowed=['xp','coins','hearts','streak','solved','current_unit']; const fields=allowed.filter(k=>Number.isInteger(req.body[k])); if(!fields.length)return res.status(400).json({error:'Nenhuma alteração.'}); const set=fields.map(k=>`${k}=@${k}`).join(','); db.prepare(`UPDATE students SET ${set},updated_at=CURRENT_TIMESTAMP WHERE id=@id`).run({...req.body,id:req.params.id}); res.json(db.prepare('SELECT * FROM students WHERE id=?').get(req.params.id));});
app.use(express.static(path.join(__dirname,'dist'))); app.use((req,res)=>res.sendFile(path.join(__dirname,'dist/index.html')));
app.listen(3000,()=>console.log('EquaQuest em http://localhost:3000'));
