import './style.css';

const units = [
  { n: 1, title: 'O equilíbrio', desc: 'Igualdade, incógnita e soluções', color: 'coral', nodes: ['A balança', 'Descubra o x', 'Teste a solução'], icon: '⚖️' },
  { n: 2, title: 'Operações inversas', desc: 'Desfaça cada movimento', color: 'blue', nodes: ['Somar e subtrair', 'Faça nos dois lados', 'Guardião'], icon: '↔' },
  { n: 3, title: 'Multiplicar e dividir', desc: 'Novos caminhos para o x', color: 'purple', nodes: ['Multiplicação', 'Divisão', 'Guardião'], icon: '×' },
  { n: 4, title: 'Duas etapas', desc: 'Uma transformação de cada vez', color: 'gold', nodes: ['Desfazer', 'Organizar', 'Guardião'], icon: '✦' },
  { n: 5, title: 'Distributividade', desc: 'Abra os parênteses', color: 'green', nodes: ['Distribuir', 'Simplificar', 'Guardião'], icon: '⌁' },
  { n: 6, title: 'x nos dois lados', desc: 'Mantenha a balança estável', color: 'pink', nodes: ['Reunir termos', 'Equilibrar', 'Guardião'], icon: '≡' },
  { n: 7, title: 'Mestre das equações', desc: 'O desafio final', color: 'navy', nodes: ['A prova final'], icon: '♛' },
];
const lessonBank = {
  1: { guided:'x + 5 = 12', op:'−5', result:'7', practice:'x − 4 = 10', answer:'14', explain:'some 4 aos dois lados', left:x=>x-4, right:10 },
  2: { guided:'x + 7 = 15', op:'−7', result:'8', practice:'x − 6 = 11', answer:'17', explain:'some 6 aos dois lados', left:x=>x-6, right:11 },
  3: { guided:'3x = 15', op:'÷3', result:'5', practice:'x / 4 = 6', answer:'24', explain:'multiplique os dois lados por 4', left:x=>x/4, right:6 },
  4: { guided:'2x + 4 = 14', op:'−4', result:'5', practice:'3x − 6 = 15', answer:'7', explain:'some 6 e depois divida por 3', left:x=>3*x-6, right:15 },
};
const questionBank = {
  1: [lessonBank[1], {guided:'x + 3 = 8',op:'−3',result:'5',practice:'x − 2 = 9',answer:'11',explain:'some 2 aos dois lados',left:x=>x-2,right:9}],
  2: [lessonBank[2], {guided:'x + 4 = 13',op:'−4',result:'9',practice:'x − 8 = 5',answer:'13',explain:'some 8 aos dois lados',left:x=>x-8,right:5}],
  3: [lessonBank[3], {guided:'2x = 18',op:'÷2',result:'9',practice:'x / 3 = 7',answer:'21',explain:'multiplique os dois lados por 3',left:x=>x/3,right:7}],
  4: [lessonBank[4], {guided:'2x + 6 = 16',op:'−6',result:'5',practice:'2x + 4 = 18',answer:'7',explain:'some 4 e depois divida por 2',left:x=>2*x+4,right:18}],
};
let questionIndex=0;
function currentLesson(){const list=questionBank[state.current]||questionBank[4];return list[questionIndex%list.length];}
function recordAttempt(answer,correct){if(student)fetch('/api/attempts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student_id:student.id,unit:state.current,answer,correct})}).catch(()=>{});}
async function teacherDemo(){const name=prompt('Nome do professor','Professor de Matemática')||'Professor de Matemática';app.innerHTML=`<main class="teacher-page"><div class="teacher-head"><div class="brand"><span class="brand-mark">=</span><span>equ<span>a</span>quest</span></div><button class="back" onclick="login()">← Voltar</button></div><div class="teacher-card"><p class="eyebrow">ÁREA DO PROFESSOR</p><h1>Turmas e trilhas</h1><p>Crie uma turma e escolha quais unidades os alunos devem estudar.</p><button class="demo-button" onclick="createMock()">Carregar dados de demonstração</button><form onsubmit="createClass(event,'${name.replace(/'/g,"\\'")}')"><input name="className" required placeholder="Nome da turma, ex.: 7º ano A"><button class="primary">Criar turma <span>→</span></button></form><div id="class-list">Carregando turmas...</div></div></main>`;loadClasses()}
function teacherLogin(){app.innerHTML=`<main class="login"><div class="login-card"><button class="back" onclick="login()">← Voltar</button><div class="brand"><span class="brand-mark">=</span><span>equ<span>a</span>quest</span></div><h1>Login do professor</h1><p>Entre para gerenciar turmas e acompanhar a turma.</p><form onsubmit="teacherSubmit(event)"><label>Nome<input name="name" required value="Professor Demo"></label><label>E-mail<input name="email" type="email" required value="professor.demo@eququest.local"></label><button class="primary">Entrar <span>→</span></button></form><button class="demo-button" onclick="teacherSubmitDemo()">Entrar com professor de demonstração</button></div></main>`}
function teacherSubmitDemo(){localStorage.setItem('eququest_teacher',JSON.stringify({name:'Professor Demo',email:'professor.demo@eququest.local'}));teacherDemoWithName('Professor Demo')}
function teacherSubmit(e){e.preventDefault();const f=new FormData(e.target);localStorage.setItem('eququest_teacher',JSON.stringify({name:f.get('name'),email:f.get('email')}));teacherDemoWithName(f.get('name'))}
function teacherDemoWithName(name){app.innerHTML=`<main class="teacher-page"><div class="teacher-head"><div class="brand"><span class="brand-mark">=</span><span>equ<span>a</span>quest</span></div><button class="back" onclick="teacherLogout()">Sair</button></div><div class="teacher-card"><p class="eyebrow">ÁREA DO PROFESSOR</p><h1>Olá, ${name}.</h1><p>Gerencie turmas, trilhas e acompanhamento.</p><button class="demo-button" onclick="createMock()">Carregar dados de demonstração</button><form onsubmit="createClass(event,'${name.replace(/'/g,"\\'")}')"><input name="className" required placeholder="Nome da turma, ex.: 7º ano A"><button class="primary">Criar turma <span>→</span></button></form><div class="teacher-preferences"><b>Preferências</b><label><input type="checkbox" checked onchange="saveTeacherPreference('feedback',this.checked)"> Mostrar feedback detalhado</label><label><input type="checkbox" checked onchange="saveTeacherPreference('difficulty',this.checked)"> Recomendar revisão por dificuldade</label></div><div id="class-list">Carregando turmas...</div></div></main>`;loadClasses()}
function teacherLogout(){localStorage.removeItem('eququest_teacher');login()}
function saveTeacherPreference(key,value){const p=JSON.parse(localStorage.getItem('eququest_teacher_preferences')||'{}');p[key]=value;localStorage.setItem('eququest_teacher_preferences',JSON.stringify(p))}
function logout(){student=null;localStorage.removeItem('eququest_student');localStorage.removeItem('eququest');login()}
async function createClass(e,teacher){e.preventDefault();const name=new FormData(e.target).get('className');await fetch('/api/classes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,teacher})});e.target.reset();loadClasses()}
async function createMock(){await fetch('/api/mock',{method:'POST'});loadClasses();alert('Dados de demonstração criados.');}
async function loadClasses(){const el=document.querySelector('#class-list');try{const r=await fetch('/api/classes');if(!r.ok)throw new Error('Servidor indisponível');const classes=await r.json();if(el)el.innerHTML=classes.map(c=>`<div class="class-row"><button class="class-open" onclick="showClass(${c.id},'${c.name.replace(/'/g,"\\'")}')"><b>${c.name}</b><small>${c.students} alunos</small></button><button class="open-panel" onclick="showClass(${c.id},'${c.name.replace(/'/g,"\\'")}')">Abrir painel →</button><select onchange="assignUnit(${c.id},this.value)"><option>Adicionar trilha</option>${units.map(u=>`<option value="${u.n}">Unidade ${u.n} · ${u.title}</option>`).join('')}</select></div>`).join('')||'<p>Nenhuma turma criada.</p>'}catch(e){if(el)el.innerHTML='<p class="server-error">Não foi possível carregar as turmas. Execute <code>npm run dev</code> e atualize a página.</p>'}}
async function showClass(id,name){const el=document.querySelector('#class-list');const [rr,ar]=await Promise.all([fetch(`/api/classes/${id}/overview`),fetch(`/api/classes/${id}/activities`)]);const data=await rr.json(),activities=await ar.json();const students=data.students||[],avg=students.length?Math.round(students.reduce((a,s)=>a+s.accuracy,0)/students.length):0,attention=students.filter(s=>s.accuracy<60).length;el.innerHTML=`<div class="class-overview"><button class="back-link" onclick="loadClasses()">← Voltar para turmas</button><h3>${name}</h3><div class="class-metrics"><div><b>${students.length}</b><small>alunos</small></div><div><b>${avg}%</b><small>acerto médio</small></div><div><b>${attention}</b><small>precisam de atenção</small></div></div><div class="member-box"><b>Adicionar aluno</b><form onsubmit="addStudentToClass(event,${id},'${name.replace(/'/g,"\\'")}')"><input name="email" type="email" required placeholder="E-mail do aluno"><button class="primary">Adicionar <span>→</span></button></form><small>Use um e-mail já cadastrado no EquaQuest.</small></div><div class="activity-box"><b>Nova atividade</b><form onsubmit="createActivity(event,${id},'${name.replace(/'/g,"\\'")}')"><input name="title" required placeholder="Ex.: Revisão de operações inversas"><select name="unit">${units.map(u=>`<option value="${u.n}">Unidade ${u.n}</option>`).join('')}</select><input name="due_date" type="date"><button class="primary">Atribuir <span>→</span></button></form><div class="activity-list">${activities.map(a=>`<div><b>${a.title}</b><span>Unidade ${a.unit}${a.due_date?' · até '+a.due_date:''}</span></div>`).join('')||'<small>Nenhuma atividade criada.</small>'}</div></div><div class="student-heading"><b>Alunos</b><span>Desempenho e recomendação</span></div>${students.map(s=>{const weak=s.weakest?.unit?units[s.weakest.unit-1]?.title:'Sem dados';return `<div class="student-row"><div><b>${s.name}</b><small>${s.email}</small></div><span>Unidade ${s.current_unit}</span><strong>${s.accuracy}% acerto</strong><em class="${s.accuracy<60?'needs-help':''}">${s.accuracy<60?'Precisa revisar: ':'Praticar: '}${weak}</em></div>`}).join('')||'<p>Esta turma ainda não tem alunos.</p>'}</div>`}
async function addStudentToClass(e,classId,name){e.preventDefault();const email=new FormData(e.target).get('email'),r=await fetch(`/api/classes/${classId}/members`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});if(!r.ok){alert((await r.json()).error);return}showClass(classId,name)}
async function createActivity(e,classId,name){e.preventDefault();const f=new FormData(e.target);await fetch(`/api/classes/${classId}/activities`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:f.get('title'),unit:Number(f.get('unit')),due_date:f.get('due_date')})});showClass(classId,name)}
async function assignUnit(id,unit){if(unit!=='Adicionar trilha')await fetch(`/api/classes/${id}/assignments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unit:Number(unit)})})}

const initial = { xp: 1250, coins: 230, hearts: 4, streak: 5, solved: 8, current: 1, stars: [2], bestStreak: 4 };
let state = JSON.parse(localStorage.getItem('eququest') || 'null') || initial;
let lessonStep = 0;
let feedback = '';
let selected = null;
let answerValue = '';
let pendingUnitAdvance = false;
let lessonRound = 1;
let student = JSON.parse(localStorage.getItem('eququest_student') || 'null');
const app = document.querySelector('#app');

async function save() { localStorage.setItem('eququest', JSON.stringify(state)); if(student) { const r=await fetch(`/api/students/${student.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({xp:state.xp,coins:state.coins,hearts:state.hearts,streak:state.streak,solved:state.solved,current_unit:state.current})}).catch(()=>null); if(r?.ok) student=await r.json(); } }
function icon(name) { return ({heart:'♥', coin:'◆', flame:'✦'})[name] || ''; }
function login(){app.innerHTML=`<main class="login"><div class="login-card"><div class="brand"><span class="brand-mark">=</span><span>equ<span>a</span>quest</span></div><h1>Perfil do aluno</h1><p>Entre para salvar XP, conquistas e progresso.</p><form onsubmit="loginSubmit(event)"><label>Nome<input name="name" required placeholder="Seu nome"></label><label>E-mail<input name="email" type="email" required placeholder="voce@escola.com"></label><button class="primary">Entrar <span>→</span></button></form><button class="demo-button" onclick="loginDemo()">Entrar como aluno de teste</button><button class="demo-button" onclick="teacherLogin()">Login do professor</button></div></main>`}
async function loginDemo(){const r=await fetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Aluno de teste',email:'teste@eququest.local'})});if(!r.ok){alert('Inicie o servidor com: node server.js');return}student=await r.json();state={xp:student.xp,coins:student.coins,hearts:student.hearts,streak:student.streak,solved:student.solved,current:student.current_unit,stars:[]};localStorage.setItem('eququest_student',JSON.stringify(student));localStorage.setItem('eququest',JSON.stringify(state));render()}
async function loginSubmit(e){e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),email:f.get('email')})});if(!r.ok){alert('Não foi possível criar o perfil.');return}student=await r.json();state={xp:student.xp,coins:student.coins,hearts:student.hearts,streak:student.streak,solved:student.solved,current:student.current_unit,stars:[]};localStorage.setItem('eququest_student',JSON.stringify(student));save();render()}
function render() {
  app.innerHTML = `<div class="shell">
    <header class="topbar"><div class="brand" onclick="window.location.reload()"><span class="brand-mark">=</span><span>equ<span>a</span>quest</span></div><div class="top-stats"><div class="stat"><b class="heart">♥</b><strong>${state.hearts}</strong></div><div class="stat"><b class="coin">◆</b><strong>${state.coins}</strong></div><div class="stat"><b class="flame">✦</b><strong>${state.streak}</strong></div><div class="avatar">${student?.name?.[0]?.toUpperCase()||'A'}</div><button class="logout" onclick="logout()">Sair</button></div></header>
    <main><section class="hero"><div><p class="eyebrow">UNIDADE ${state.current}</p><h1>Resolver <em>equações.</em></h1><p class="sub">Comece pela lição atual e avance no seu ritmo.</p><button class="primary" onclick="startLesson()">Abrir lição <span>→</span></button></div><div class="hero-art"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="balance"><div class="beam"><span>+</span><span>−</span></div><div class="stand"></div><div class="base"></div><div class="pan left">x + 3</div><div class="pan right">8</div></div><div class="spark s1">✦</div><div class="spark s2">·</div></div></section>
    <section class="dashboard"><div class="level"><div class="level-head"><span>NÍVEL 7</span><b>${state.xp.toLocaleString('pt-BR')} / 1.500 XP</b></div><div class="progress"><i style="width:${Math.min(100,(state.xp%500)/5)}%"></i></div></div><div class="dash-item"><div class="dash-icon streak-icon">✦</div><div><small>OFENSIVA</small><b>${state.streak} dias</b></div></div><div class="dash-item"><div class="dash-icon">✓</div><div><small>RESOLVIDAS</small><b>${state.solved} equações</b></div></div></section>
    <section class="path-section"><div class="section-title"><div><p class="eyebrow">CONTEÚDO</p><h2>Trilha de equações</h2></div><span class="path-count">${state.current} de 7 unidades</span></div><div class="path">${units.map((u,i)=>unitCard(u,i)).join('')}</div></section><section class="difficulty panel"><div class="panel-title"><div><p class="eyebrow">SEU DESEMPENHO</p><h3>Onde praticar mais</h3></div></div><div id="difficulty-panel"><p class="empty-performance">Carregando desempenho...</p></div></section><section class="student-classes panel"><div class="panel-title"><h3>Turmas e trilhas atribuídas</h3></div><div id="student-classes">Carregando...</div></section>${recommendations()}
    <section class="bottom-grid"><div class="panel achievements"><div class="panel-title"><h3>Conquistas recentes</h3><a>Ver todas →</a></div><div class="achievement-row"><div class="badge badge-coral">✧</div><div><b>Primeiros passos</b><p>Resolva sua primeira equação</p></div><span class="done">✓</span></div><div class="achievement-row faded"><div class="badge badge-gold">♟</div><div><b>Equilibrista</b><p>Resolva 10 equações corretamente</p></div><span>${state.solved}/10</span></div></div><div class="panel tip"><div class="tip-shape">?</div><div><p class="eyebrow">DICA DO DIA</p><h3>A balança sempre conta a verdade.</h3><p>Faça a mesma operação dos dois lados para manter a igualdade.</p></div></div></section>
    </main><footer><span>equ<span>a</span>quest</span><span>Aprender é encontrar o equilíbrio.</span></footer>
  </div>`;
}
function unitCard(u,i) { const locked=i>state.current; const active=i===state.current-1; return `<article class="unit ${u.color} ${locked?'locked':''} ${active?'active':''}"><div class="unit-top"><div class="unit-icon">${locked?'▣':u.icon}</div><div><small>UNIDADE ${u.n}</small><h3>${u.title}</h3><p>${u.desc}</p></div>${active?'<span class="now">AGORA</span>':''}</div><div class="nodes">${u.nodes.map((x,j)=>`<div class="node ${j===u.nodes.length-1?'boss':''} ${locked?'node-lock':''}"><span>${locked?'×':j===u.nodes.length-1?'♛':j+1}</span><label>${x}</label>${!locked&&j<1&&active?'<b>✓</b>':''}</div>`).join('')}</div>${active?'<button class="unit-action" onclick="startLesson()">Começar lição <span>→</span></button>':''}</article>` }
function recommendations(){const u=units[Math.min(state.current-1,units.length-1)];return `<section class="recommendations"><div class="section-title"><div><p class="eyebrow">RECOMENDAÇÕES</p><h2>Próximos passos</h2></div><span class="path-count">Baseado no seu progresso</span></div><div class="recommendation-grid"><article class="recommendation basic"><div class="rec-label">REFORÇO BÁSICO</div><h3>Revise: ${u.title}</h3><p>Atividade curta para firmar o conceito.</p><button onclick="startLesson()">Revisar <span>→</span></button></article><article class="recommendation medium"><div class="rec-label">PRÁTICA</div><h3>Resolva mais uma</h3><p>Treine a habilidade com menos dicas.</p><button onclick="startLesson()">Praticar <span>→</span></button></article><article class="recommendation advanced"><div class="rec-label">DESAFIO AVANÇADO</div><h3>Guardião da unidade</h3><p>Combine as habilidades da unidade.</p><button onclick="startLesson()">Desafiar <span>→</span></button></article></div></section>`}
async function loadPerformance(){if(!student)return;const r=await fetch(`/api/students/${student.id}/performance`).catch(()=>null);if(!r?.ok)return;const data=await r.json(),el=document.querySelector('#difficulty-panel');if(!el)return;const rows=data.byUnit.filter(x=>x.unit).slice(0,3);el.innerHTML=rows.length?rows.map(x=>{const u=units[x.unit-1],rate=Math.round((x.correct/x.attempts)*100);return `<div class="difficulty-row"><b>${u?.title||'Unidade '+x.unit}</b><small>${rate}% de acerto · ${x.attempts} tentativas</small><i style="width:${rate}%"></i></div>`}).join(''):'<p class="empty-performance">Resolva algumas questões para identificar seus pontos de atenção.</p>'}
async function loadStudentClasses(){if(!student)return;const r=await fetch(`/api/students/${student.id}/classes`).catch(()=>null),el=document.querySelector('#student-classes');if(!r?.ok||!el)return;const rows=await r.json();el.innerHTML=rows.length?rows.map(x=>`<div><b>${x.name}</b><span>${x.unit?'Unidade '+x.unit:'Nenhuma trilha atribuída'}</span></div>`).join(''):'<p>Nenhuma turma vinculada.</p>'}

function startLesson(){ lessonStep=0; feedback=''; selected=null; answerValue=''; pendingUnitAdvance=false; lessonRound=1; const list=questionBank[state.current]||questionBank[4]; questionIndex=Math.floor(Math.random()*list.length); renderLesson(); }
function nextLessonStep(step){ lessonStep=step; renderLesson(); }
function chooseOperation(operation){ selected=operation; renderLesson(); }
function nextAfterChoice(){ if(selected===currentLesson().op) nextLessonStep(3); }
function guidedSolution(){const q=currentLesson();if(!selected)return '';const correct=selected===q.op;return `<div class="guided-solution"><small>SOLUÇÃO A PARTIR DA SUA ESCOLHA</small>${correct?`<div>${q.guided}</div><div class="operation">${q.op} nos dois lados</div><div>${q.guided.replace(' = ',' ' + q.op + ' = ' + q.op + ' ')}</div><div class="result">x = ${q.result}</div>`:`<div>${q.guided}</div><div class="operation">${selected} nos dois lados</div><div>Essa operação não desfaz o primeiro passo.</div><div class="result">A operação indicada é ${q.op}.</div>`}</div>`}
function finishLesson(){if(lessonRound<5){lessonRound++;feedback='';selected=null;answerValue='';const list=questionBank[state.current]||questionBank[4];questionIndex=Math.floor(Math.random()*list.length);renderLesson();return}if(pendingUnitAdvance){state.current=Math.min(7,state.current+1);pendingUnitAdvance=false;save()}answerValue='';app.innerHTML=`<div class="lesson-shell"><main class="lesson"><div class="lesson-card completion"><div class="completion-icon">✓</div><div class="step-tag">ATIVIDADE CONCLUÍDA</div><h1>5 questões resolvidas.</h1><p>Você manteve os dois lados da balança iguais em uma atividade completa.</p><div class="reward"><span>+50 XP</span><span>+25 moedas</span><span>★★★</span></div><button class="primary" onclick="render()">Voltar para a trilha <span>→</span></button></div></main></div>`}
function updateBalance(value){const q=currentLesson(),x=Number(value),left=Number.isFinite(x)?q.left(x):'?',right=q.right,diff=Number.isFinite(x)?left-right:0;const beam=document.querySelector('.practice-beam');if(beam)beam.style.transform=`rotate(${Math.max(-12,Math.min(12,diff*1.5))}deg)`;const l=document.querySelector('.balance-left-value'),r=document.querySelector('.balance-right-value');if(l)l.textContent=left;if(r)r.textContent=right;}
function renderLesson(){ app.innerHTML=`<div class="lesson-shell"><header class="lesson-top"><button class="back" onclick="render()">←</button><div class="lesson-progress"><span style="width:${(lessonStep/4)*100}%"></span></div><div class="lesson-hearts">♥ ${state.hearts}</div></header><main class="lesson"><p class="eyebrow">UNIDADE ${state.current} · ${units[state.current-1]?.title||'O EQUILÍBRIO'}</p>${lessonStep===0?intro():lessonStep===1?explain():lessonStep===2?guided():practice()}</main></div>`; }
function intro(){return `<div class="lesson-card"><div class="lesson-illustration"><div class="mini-balance"><div class="mini-beam"></div><div class="mini-stand"></div><div class="mini-pan p1">x + 3</div><div class="mini-pan p2">8</div></div></div><h1>Uma equação é uma<br/><em>balança em equilíbrio.</em></h1><p>Os dois lados têm o mesmo valor. Para descobrir o <b>x</b>, vamos transformar a equação sem desequilibrá-la.</p><button class="primary" onclick="nextLessonStep(1)">Continuar <span>→</span></button></div>`}
function explain(){return `<div class="lesson-card"><div class="step-tag">NOVA HABILIDADE</div><h1>Desfaça o que foi<br/><em>adicionado.</em></h1><div class="equation large">x + 3 <strong>=</strong> 8</div><p>Para remover o <b>+3</b>, usamos a operação inversa: <b>−3</b>. E fazemos isso nos dois membros.</p><div class="transform">x + 3 <span>− 3</span> <strong>=</strong> 8 <span>− 3</span></div><button class="primary" onclick="nextLessonStep(2)">Entendi <span>→</span></button></div>`}
function guided(){const q=currentLesson();const choices=[q.op,q.op==='−5'?'+5':q.op==='−3'?'+3':q.op==='÷3'?'×3':'×2',q.op[0]==='−'?'×'+q.op.slice(1):'−'+q.op.slice(1),'÷'+q.op.slice(1)];return `<div class="lesson-card"><div class="step-tag">INTERAÇÃO GUIADA · 1/2</div><h1>Qual movimento<br/><em>mantém tudo igual?</em></h1><div class="equation">${q.guided.replace(' = ',' <strong>=</strong> ')}</div><p>Escolha a operação que desfaz o primeiro passo.</p><div class="choices">${[...new Set(choices)].map(x=>`<button class="choice ${selected===x?'selected':''} ${selected&&x===q.op?'correct-option':''}" onclick="chooseOperation('${x}')">${x}</button>`).join('')}</div>${selected?`<div class="feedback ${selected===q.op?'good':''}"><b>${selected===q.op?'Isso! A balança continua equilibrada.':'Quase! Veja o efeito dessa operação.'}</b><span>${selected===q.op?'A transformação mantém a igualdade.':'Essa operação não desfaz o primeiro passo.'}</span></div>${guidedSolution()}`:''}<button class="primary ${selected!==q.op?'disabled':''}" onclick="nextAfterChoice()" >Próximo passo <span>→</span></button></div>`}
function practice(){const q=currentLesson(), shown=answerValue, answer=Number(q.answer), left=shown===''?'?':q.left(Number(shown)), right=q.right, angle=shown===''?0:Math.max(-12,Math.min(12,(Number(left)-right)*1.5));return `<div class="lesson-card"><div class="step-tag">PRÁTICA ${lessonRound}/5 · +10 XP</div><h1>Agora é com você.</h1><p>Digite um valor e observe a balança:</p><div class="practice-balance"><div class="practice-beam" style="transform:rotate(${angle}deg)"><div class="practice-pan balance-left-value">${left}</div><div class="practice-pan balance-right-value">${right}</div></div><div class="practice-pivot"></div><small>os dois lados precisam ter o mesmo valor</small></div><div class="equation large">${q.practice.replace(' = ',' <strong>=</strong> ')}</div><div class="answer-row"><span>x =</span><input id="answer" type="number" autofocus placeholder="?" value="${shown}" oninput="updateBalance(this.value)"/><button class="primary" onclick="checkAnswer()">Conferir <span>→</span></button></div>${feedback?`<div class="feedback ${feedback[0]==='✓'?'good':''}"><b>${feedback}</b><span>${feedback[0]==='✓'?'Resposta correta. Você ganhou +10 XP e +5 moedas.':'Você respondeu '+shown+'. A solução é x = '+q.answer+'. Para resolver, '+q.explain+'.'}</span></div>`:''}${feedback[0]==='✓'?'<button class="primary finish-button" onclick="finishLesson()">Concluir lição <span>→</span></button>':''}</div>`}
function checkAnswer(){const a=document.querySelector('#answer').value;answerValue=a;const correct=a===currentLesson().answer;recordAttempt(a,correct);if(correct){state.xp+=10;state.coins+=5;state.solved++;pendingUnitAdvance=true;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);state.stars=[3];save();feedback='✓ Muito bem!';renderLesson()}else{state.hearts=Math.max(0,state.hearts-1);state.streak=0;save();feedback='Ainda não: a balança ficou desequilibrada.';renderLesson()}}
async function boot(){if(!student){login();return}const r=await fetch(`/api/students/${student.id}`).catch(()=>null);if(r?.ok){student=await r.json();state={xp:student.xp,coins:student.coins,hearts:student.hearts,streak:student.streak,solved:student.solved,current:student.current_unit,stars:[]};localStorage.setItem('eququest',JSON.stringify(state));}render();loadPerformance()}
window.startLesson=startLesson; window.render=render; window.renderLesson=renderLesson; window.checkAnswer=checkAnswer; window.login=login; window.loginSubmit=loginSubmit; window.loginDemo=loginDemo; window.logout=logout; window.teacherDemo=teacherDemo; window.teacherLogin=teacherLogin; window.teacherSubmit=teacherSubmit; window.teacherSubmitDemo=teacherSubmitDemo; window.teacherLogout=teacherLogout; window.saveTeacherPreference=saveTeacherPreference; window.createMock=createMock; window.createClass=createClass; window.assignUnit=assignUnit; window.showClass=showClass; window.addStudentToClass=addStudentToClass; window.createActivity=createActivity; window.nextLessonStep=nextLessonStep; window.chooseOperation=chooseOperation; window.nextAfterChoice=nextAfterChoice; window.updateBalance=updateBalance; window.finishLesson=finishLesson; boot(); loadPerformance(); loadStudentClasses();
