import './style.css';

const units = [
  { n: 1, title: 'O equilíbrio', desc: 'Igualdade, incógnita e soluções', color: 'coral', nodes: ['A balança', 'Descubra o x', 'Teste a solução'], icon: '⚖️' },
  { n: 2, title: 'Operações inversas', desc: 'Desfaça cada movimento', color: 'blue', nodes: ['Somar e subtrair', 'Faça nos dois lados', 'Guardião'], icon: '↔' },
  { n: 3, title: 'Multiplicar e dividir', desc: 'Novos caminhos para o x', color: 'purple', nodes: ['Multiplicação', 'Divisão', 'Guardião'], icon: '×' },
  { n: 4, title: 'Duas etapas', desc: 'Uma transformação de cada vez', color: 'gold', nodes: ['Desfazer', 'Organizar', 'Guardião'], icon: '✦' },
  { n: 5, title: 'Distributividade', desc: 'Abra os parênteses', color: 'green', nodes: ['Distribuir', 'Simplificar', 'Guardião'], icon: '⌁' },
  { n: 6, title: 'x nos dois lados', desc: 'Mantenha a balança estável', color: 'pink', nodes: ['Reunir termos', 'Equilibrar', 'Guardião'], icon: '≡' },
  { n: 7, title: 'Mestre das equações', desc: 'O desafio final', color: 'navy', nodes: ['A prova final'], icon: '♛' },
];

const initial = { xp: 1250, coins: 230, hearts: 4, streak: 5, solved: 8, current: 1, stars: [2], bestStreak: 4 };
let state = JSON.parse(localStorage.getItem('eququest') || 'null') || initial;
let lessonStep = 0;
let feedback = '';
let selected = null;
let student = JSON.parse(localStorage.getItem('eququest_student') || 'null');
const app = document.querySelector('#app');

async function save() { localStorage.setItem('eququest', JSON.stringify(state)); if(student) { const r=await fetch(`/api/students/${student.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({xp:state.xp,coins:state.coins,hearts:state.hearts,streak:state.streak,solved:state.solved,current_unit:state.current})}).catch(()=>null); if(r?.ok) student=await r.json(); } }
function icon(name) { return ({heart:'♥', coin:'◆', flame:'✦'})[name] || ''; }
function login(){app.innerHTML=`<main class="login"><div class="login-card"><div class="brand"><span class="brand-mark">=</span><span>equ<span>a</span>quest</span></div><h1>Perfil do aluno</h1><p>Entre para salvar XP, conquistas e progresso.</p><form onsubmit="loginSubmit(event)"><label>Nome<input name="name" required placeholder="Seu nome"></label><label>E-mail<input name="email" type="email" required placeholder="voce@escola.com"></label><button class="primary">Entrar <span>→</span></button></form><button class="demo-button" onclick="loginDemo()">Entrar como aluno de teste</button></div></main>`}
async function loginDemo(){const r=await fetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Aluno de teste',email:'teste@eququest.local'})});if(!r.ok){alert('Inicie o servidor com: node server.js');return}student=await r.json();state={xp:student.xp,coins:student.coins,hearts:student.hearts,streak:student.streak,solved:student.solved,current:student.current_unit,stars:[]};localStorage.setItem('eququest_student',JSON.stringify(student));localStorage.setItem('eququest',JSON.stringify(state));render()}
async function loginSubmit(e){e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),email:f.get('email')})});if(!r.ok){alert('Não foi possível criar o perfil.');return}student=await r.json();state={xp:student.xp,coins:student.coins,hearts:student.hearts,streak:student.streak,solved:student.solved,current:student.current_unit,stars:[]};localStorage.setItem('eququest_student',JSON.stringify(student));save();render()}
function render() {
  app.innerHTML = `<div class="shell">
    <header class="topbar"><div class="brand" onclick="window.location.reload()"><span class="brand-mark">=</span><span>equ<span>a</span>quest</span></div><div class="top-stats"><div class="stat"><b class="heart">♥</b><strong>${state.hearts}</strong></div><div class="stat"><b class="coin">◆</b><strong>${state.coins}</strong></div><div class="stat"><b class="flame">✦</b><strong>${state.streak}</strong></div><div class="avatar">V</div></div></header>
    <main><section class="hero"><div><p class="eyebrow">UNIDADE ${state.current}</p><h1>Resolver <em>equações.</em></h1><p class="sub">Comece pela lição atual e avance no seu ritmo.</p><button class="primary" onclick="startLesson()">Abrir lição <span>→</span></button></div><div class="hero-art"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="balance"><div class="beam"><span>+</span><span>−</span></div><div class="stand"></div><div class="base"></div><div class="pan left">x + 3</div><div class="pan right">8</div></div><div class="spark s1">✦</div><div class="spark s2">·</div></div></section>
    <section class="dashboard"><div class="level"><div class="level-head"><span>NÍVEL 7</span><b>${state.xp.toLocaleString('pt-BR')} / 1.500 XP</b></div><div class="progress"><i style="width:${Math.min(100,(state.xp%500)/5)}%"></i></div></div><div class="dash-item"><div class="dash-icon streak-icon">✦</div><div><small>OFENSIVA</small><b>${state.streak} dias</b></div></div><div class="dash-item"><div class="dash-icon">✓</div><div><small>RESOLVIDAS</small><b>${state.solved} equações</b></div></div></section>
    <section class="path-section"><div class="section-title"><div><p class="eyebrow">CONTEÚDO</p><h2>Trilha de equações</h2></div><span class="path-count">${state.current} de 7 unidades</span></div><div class="path">${units.map((u,i)=>unitCard(u,i)).join('')}</div></section>
    <section class="bottom-grid"><div class="panel achievements"><div class="panel-title"><h3>Conquistas recentes</h3><a>Ver todas →</a></div><div class="achievement-row"><div class="badge badge-coral">✧</div><div><b>Primeiros passos</b><p>Resolva sua primeira equação</p></div><span class="done">✓</span></div><div class="achievement-row faded"><div class="badge badge-gold">♟</div><div><b>Equilibrista</b><p>Resolva 10 equações corretamente</p></div><span>${state.solved}/10</span></div></div><div class="panel tip"><div class="tip-shape">?</div><div><p class="eyebrow">DICA DO DIA</p><h3>A balança sempre conta a verdade.</h3><p>Faça a mesma operação dos dois lados para manter a igualdade.</p></div></div></section>
    </main><footer><span>equ<span>a</span>quest</span><span>Aprender é encontrar o equilíbrio.</span></footer>
  </div>`;
}
function unitCard(u,i) { const locked=i>state.current; const active=i===state.current-1; return `<article class="unit ${u.color} ${locked?'locked':''} ${active?'active':''}"><div class="unit-top"><div class="unit-icon">${locked?'▣':u.icon}</div><div><small>UNIDADE ${u.n}</small><h3>${u.title}</h3><p>${u.desc}</p></div>${active?'<span class="now">AGORA</span>':''}</div><div class="nodes">${u.nodes.map((x,j)=>`<div class="node ${j===u.nodes.length-1?'boss':''} ${locked?'node-lock':''}"><span>${locked?'×':j===u.nodes.length-1?'♛':j+1}</span><label>${x}</label>${!locked&&j<1&&active?'<b>✓</b>':''}</div>`).join('')}</div>${active?'<button class="unit-action" onclick="startLesson()">Começar lição <span>→</span></button>':''}</article>` }

function startLesson(){ lessonStep=0; feedback=''; selected=null; renderLesson(); }
function nextLessonStep(step){ lessonStep=step; renderLesson(); }
function chooseOperation(operation){ selected=operation; renderLesson(); }
function nextAfterChoice(){ if(selected==='−5') nextLessonStep(3); }
function updateBalance(value){const x=Number(value);const left=Number.isFinite(x)?x-4:'?';const right=10;const diff=Number.isFinite(x)?left-right:0;const beam=document.querySelector('.practice-beam');if(beam)beam.style.transform=`rotate(${Math.max(-12,Math.min(12,diff*1.5))}deg)`;const l=document.querySelector('.balance-left-value'),r=document.querySelector('.balance-right-value');if(l)l.textContent=left;if(r)r.textContent=right;}
function renderLesson(){ app.innerHTML=`<div class="lesson-shell"><header class="lesson-top"><button class="back" onclick="render()">←</button><div class="lesson-progress"><span style="width:${(lessonStep/4)*100}%"></span></div><div class="lesson-hearts">♥ ${state.hearts}</div></header><main class="lesson"><p class="eyebrow">UNIDADE 1 · O EQUILÍBRIO</p>${lessonStep===0?intro():lessonStep===1?explain():lessonStep===2?guided():practice()}</main></div>`; }
function intro(){return `<div class="lesson-card"><div class="lesson-illustration"><div class="mini-balance"><div class="mini-beam"></div><div class="mini-stand"></div><div class="mini-pan p1">x + 3</div><div class="mini-pan p2">8</div></div></div><h1>Uma equação é uma<br/><em>balança em equilíbrio.</em></h1><p>Os dois lados têm o mesmo valor. Para descobrir o <b>x</b>, vamos transformar a equação sem desequilibrá-la.</p><button class="primary" onclick="nextLessonStep(1)">Continuar <span>→</span></button></div>`}
function explain(){return `<div class="lesson-card"><div class="step-tag">NOVA HABILIDADE</div><h1>Desfaça o que foi<br/><em>adicionado.</em></h1><div class="equation large">x + 3 <strong>=</strong> 8</div><p>Para remover o <b>+3</b>, usamos a operação inversa: <b>−3</b>. E fazemos isso nos dois membros.</p><div class="transform">x + 3 <span>− 3</span> <strong>=</strong> 8 <span>− 3</span></div><button class="primary" onclick="nextLessonStep(2)">Entendi <span>→</span></button></div>`}
function guided(){return `<div class="lesson-card"><div class="step-tag">INTERAÇÃO GUIADA · 1/2</div><h1>Qual movimento<br/><em>mantém tudo igual?</em></h1><div class="equation">x + 5 <strong>=</strong> 12</div><p>Escolha a operação que desfaz o <b>+5</b>.</p><div class="choices">${['+5','−5','×5','÷5'].map(x=>`<button class="choice ${selected===x?'selected':''}" onclick="chooseOperation('${x}')">${x}</button>`).join('')}</div>${selected?`<div class="feedback ${selected==='−5'?'good':''}"><b>${selected==='−5'?'Isso! A balança continua equilibrada.':'Quase! Pense na operação inversa de adicionar.'}</b><span>${selected==='−5'?'x + 5 − 5 = 12 − 5  →  x = 7':'Tente novamente: qual operação desfaz o +5?'}</span></div>`:''}<button class="primary ${selected!=='−5'?'disabled':''}" onclick="nextAfterChoice()" >Próximo passo <span>→</span></button></div>`}
function practice(){return `<div class="lesson-card"><div class="step-tag">PRÁTICA · +10 XP</div><h1>Agora é com você.</h1><p>Digite um valor e observe a balança:</p><div class="practice-balance"><div class="practice-beam"><div class="practice-pan balance-left-value">?</div><div class="practice-pan balance-right-value">10</div></div><div class="practice-pivot"></div><small>os dois lados precisam ter o mesmo valor</small></div><div class="equation large">x − 4 <strong>=</strong> 10</div><div class="answer-row"><span>x =</span><input id="answer" type="number" autofocus placeholder="?" oninput="updateBalance(this.value)"/><button class="primary" onclick="checkAnswer()">Conferir <span>→</span></button></div>${feedback?`<div class="feedback ${feedback[0]==='✓'?'good':''}"><b>${feedback}</b><span>${feedback[0]==='✓'?'Você ganhou +10 XP e +5 moedas.':'Dica: qual operação desfaz o −4? Faça a mesma transformação nos dois lados.'}</span></div>`:''}</div>`}
function checkAnswer(){const a=document.querySelector('#answer').value;if(a==='14'){state.xp+=10;state.coins+=5;state.solved++;state.current=2;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak);state.stars=[3];save();feedback='✓ Muito bem! A solução é x = 14.';renderLesson()}else{state.hearts=Math.max(0,state.hearts-1);state.streak=0;save();feedback='Quase! Vamos olhar para o movimento.';renderLesson()}}
window.startLesson=startLesson; window.render=render; window.renderLesson=renderLesson; window.checkAnswer=checkAnswer; window.loginSubmit=loginSubmit; window.loginDemo=loginDemo; window.nextLessonStep=nextLessonStep; window.chooseOperation=chooseOperation; window.nextAfterChoice=nextAfterChoice; window.updateBalance=updateBalance; student?render():login();
